add mysql 8 compatibility
gaoyifan/docker-freeradius pull request #2
Opened 2024-02-01 13:04 UTC by yangzhaofeng

2024-02-01 23:19 UTC, gaoyifan commented
在旧版本mysql做过测试吗？看起来identity plugin会导致<8的部署失败。

2024-02-03 10:34 UTC, gaoyifan commented
pre-run 执行时会报告错误。这个错误是预期的么？
```
smartentry> pre-run script
ERROR 1064 (42000) at line 155: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @sql=IF(@@VERSION>="8.0.0",@sql_more,@sql_less)' at line 2
```

2024-02-03 12:20 UTC, yangzhaofeng commented
忘記加分號了。。。

2024-02-12 11:01 UTC, gaoyifan requested changes
修改后的版本依然有sql报错，请检查。

以下测试命令供参考
```shell
#!/bin/bash
docker rm -f mariadb
docker run -itd --name mariadb \
	--restart=unless-stopped \
	--net=host \
	--env MYSQL_ROOT_PASSWORD=radpass \
	--env MYSQL_USER=radius \
	--env MYSQL_PASSWORD=radpass \
	--env MYSQL_DATABASE=radius \
    mysql:5.5
```

```shell
docker run -it --rm --net=host -e MYSQL_HOST=127.0.0.1 -e MYSQL_ADMIN_USERNAME=root -e MYSQL_ADMIN_PASSWORD=radpass docker.io/gaoyifan/freeradius
```

2024-02-12 14:13 UTC, yangzhaofeng commented
這下弄好了

~不過4202年了誰還在用mysql 5.5啊（~

2024-02-12 14:35 UTC, yangzhaofeng commented
然後提一句，smartentry的腳本中可能需要額外加上安裝patch的命令

2024-02-13 07:48 UTC, gaoyifan commented
> 然后提一句，smartentry的脚本中可能需要额外加上安装patch的命令

感谢提醒。由于在  mods-enabled 中做了软链接， 这个 patch 已经没有意义了。稍后我来将其从仓库中移除。

2024-02-21 05:17 UTC, gaoyifan requested changes

2024-02-21 05:17 UTC, gaoyifan commented on .docker/rootfs/srv/user.sql
> +SET @sql_less2="select now();";
使用 `DO 1;` 作为占位符。这种做法相对通用，且不会带来副作用（打印日期）。
下同

2024-02-23 02:13 UTC, gaoyifan approved these changes

2024-02-23 02:13 UTC, merged